automation:
- alias: Motion Light Required Indicator
  description: Enables / disabled the motion light required indicator.
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:30:00
  - platform: sun
    event: sunset
    offset: +00:15:00
    id: sunset
  condition: []
  action:
  - if:
    - condition: trigger
      id: sunset
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.darkness_outside
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.darkness_outside
  mode: single

input_boolean:
  darkness_outside:
    name: Darkness outside
    icon: "mdi:brightness-auto"
